import { ChangeDetectorRef, EventEmitter, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { NgxTTitanColorPickerSelectorDirective } from "./ngx-ttitan-color-picker-selector.directive";
import { NgxTTitanColorPickerService } from "./ngx-ttitan-color-picker.service";
import { NgxTTitanColorPickerInputDirective } from "./ngx-ttitan-color-picker-input.directive";
import { NgxTTitanColorPickerPaletteListComponent } from "./ngx-ttitan-color-picker-palette-list/ngx-ttitan-color-picker-palette-list.component";
import { HSVA, Palette, PickerConfig, PickerOptions } from "./ngx-ttitan-color-picker.interface";
export declare class NgxTTitanColorPickerComponent implements OnInit, OnChanges {
    colorPickerService: NgxTTitanColorPickerService;
    cdr: ChangeDetectorRef;
    componentClick($event: any): void;
    options: PickerOptions;
    color: string;
    title: string;
    colorChanged: EventEmitter<string>;
    pickerInput: NgxTTitanColorPickerInputDirective;
    paletteList: NgxTTitanColorPickerPaletteListComponent;
    mainColor: NgxTTitanColorPickerSelectorDirective;
    huePicker: NgxTTitanColorPickerSelectorDirective;
    alphaPicker: NgxTTitanColorPickerSelectorDirective;
    _pickerConfig: PickerConfig;
    colorInit: boolean;
    pickerOpen: boolean;
    pickerPallets: Array<Palette>;
    hsva: HSVA;
    currentColor: string;
    currentColorMax: string;
    currentColorAlpha: string;
    currentColorAlphaZero: string;
    uuid: string;
    allowedFormats: Array<string>;
    alphaFormats: Array<string>;
    constructor(colorPickerService: NgxTTitanColorPickerService, cdr: ChangeDetectorRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    openPicker(): void;
    closePicker(): void;
    validateInputParams(): void;
    inputColorChange(color: string): void;
    updateReturnColor(): void;
    setInputValue(): void;
    setDraggersToCurrentColor(): void;
}
