import { AfterViewInit, ChangeDetectorRef, EventEmitter, OnInit } from '@angular/core';
import { NgxTTitanColorPickerSelectorDirective } from "./ngx-ttitan-color-picker-selector.directive";
import { HSVA, NgxTTitanColorPickerService, Palette } from "./ngx-ttitan-color-picker.service";
import { NgxTTitanColorPickerInputDirective } from "./ngx-ttitan-color-picker-input.directive";
import { NgxTTitanColorPickerPaletteListComponent } from "./ngx-ttitan-color-picker-palette-list/ngx-ttitan-color-picker-palette-list.component";
export declare class NgxTTitanColorPickerComponent implements OnInit, AfterViewInit {
    colorPickerService: NgxTTitanColorPickerService;
    cdr: ChangeDetectorRef;
    componentClick($event: any): void;
    pickerOpenInStart: boolean;
    alpha: boolean;
    debug: boolean;
    color: string;
    title: string;
    outFormat: string;
    inputFormat: string;
    availPallets: Array<string>;
    customPallets: Array<Palette>;
    colorChanged: EventEmitter<string>;
    pickerInput: NgxTTitanColorPickerInputDirective;
    paletteList: NgxTTitanColorPickerPaletteListComponent;
    mainColor: NgxTTitanColorPickerSelectorDirective;
    huePicker: NgxTTitanColorPickerSelectorDirective;
    alphaPicker: NgxTTitanColorPickerSelectorDirective;
    colorInit: boolean;
    pickerOpen: boolean;
    pickerPallets: Array<Palette>;
    hsva: HSVA;
    currentColor: string;
    currentColorMax: string;
    currentColorAlpha: string;
    currentColorAlphaZero: string;
    uuid: string;
    allowedFormats: Array<string>;
    constructor(colorPickerService: NgxTTitanColorPickerService, cdr: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    openPicker(): void;
    closePicker(): void;
    validateInputParams(): void;
    inputColorChange(color: string): void;
    updateReturnColor(): void;
    setInputValue(): void;
    setDraggesToCurrentColor(): void;
}
